name: Build linux profiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux-profiler-x86_64:
    runs-on: ubuntu-latest
    container: debian:10
    env:
      DOCKER_BUILDKIT: 1
    strategy:
      matrix:
        name: ['glibc']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: 'true'
      - run: apt-get update && apt-get -y install cmake clang make git curl golang libtool
      - run: cd profiler
      - run: mkdir build-release && cd build-release && cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
      - run: cd build-release && make -j16 Datadog.Profiler.Native Datadog.Linux.ApiWrapper.x64
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: profiler-libs
          path: |
            **/*.so
